version: 2

models:
  - name: stg_stations
    description: This model creates station data. 
    columns:
    - name: station_id
      description: A unique identifier for each station
      tests: 
        - not_null
        - unique
    - name: property_type
      description: The type of property for each station
      tests:
        - accepted_values:
            values: ['free_parking', 'paid_parking']
  - name: stg_trips
    description: This model creates trip data.
    columns:
    - name: start_station_id
      description: The unique identifier for the station where each trip started
      tests: 
        - not_null
  - name: trips_per_property
    description: This model aggregates data from the stg_trips and stg_stations tables to calculate the number of trips between each pair of property types
    columns:
    - name: property_type
      description: The property type associated with each pair
      tests: 
        - accepted_values:
            values: ['free_parking', 'paid_parking']
    - name: trips
      description: The number of trips for each the property type
      tests: 
        - not_null
macros:
  - name: get_end_time
    description: A macro to get end time based on start time and duration in minutes
    arguments:
      - name: start_time
        type: timestamp
        description: The time when the trip starts
      - name: duration_minutes
        type: integer
        description: Trip duration in minutes